version: "3.8"
services:
  rtaapp_panel:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: rtaapppanel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
